[env]
_.file = "{{ env.MISE_CONFIG_DIR }}/env.yaml"
ATUIN_CONFIG_DIR = "{{ env.HOME }}/.local/etc/atuin"
BAT_CONFIG_PATH = "{{ env.HOME }}/.local/etc/bat.conf"
GOPASS_CONFIG = "{{ env.HOME }}/.local/etc/gopass/config.yaml"
JIRA_TUI_CONFIG_FILE = "{{ env.HOME }}/.local/etc/jira_tui/beacon-point.yaml"
SHELDON_CONFIG_DIR = "{{ env.HOME }}/.local/etc/sheldon"
STARSHIP_CONFIG = "{{ env.HOME }}/.local/etc/starship/config.toml"
ZELLIJ_CONFIG_DIR = "{{ env.HOME }}/.local/etc/zellij"
ZSH_PATINA_CONFIG_PATH = "{{ env.HOME }}/.local/etc/zsh-patina/config.toml"
_ZO_DATA_DIR = "{{ env.HOME }}/.local/share/zoxide"

[settings]
auto_install = true
aqua.baked_registry = false
disable_backends = ["asdf", "gem", "vfox"]
exec_auto_install = true
experimental = true
idiomatic_version_file_enable_tools = []
jobs = 8
lockfile = false
npm.package_manager = "aube"
pipx.uvx = true
plugin_autoupdate_last_check_duration = "2d"
unix_default_file_shell_args = "zsh -c -o errexit"
unix_default_inline_shell_args = "zsh -c -o errexit"
use_file_shell_for_executable_tasks = true
use_versions_host = true


[tasks.run-hooks]
depends = ['mise:extract-postinstall-hooks','sheldon:source-update']

[tasks.'sheldon:source-update']
hide=true
depends=['mise:extract-postinstall-hooks']
tools.'aqua:rossmacarthur/sheldon' = ''
run = 'sheldon source --update'


# # "github:domcyrus/rustnet" = { version = "latest", os = ["linux"] }
[tools]
deno = "latest"
aube = "latest"
node = "latest"
"aqua:99designs/aws-vault"         = { version = "latest" }
"aqua:ajeetdsouza/zoxide"          = { version = "latest", postinstall = "zsh-cache-init zoxide init zsh;" }
"aqua:amir20/dtop"                 = { version = "latest", os =["linux"] }
"aqua:antonmedv/fx"                = { version = "latest" }
"aqua:astral-sh/uv"                = { version = "latest", postinstall = "zsh-cache-comp uv --generate-shell-completion zsh;" }
"aqua:atuinsh/atuin"               = { version = "latest", postinstall = "zsh-cache-init atuin init zsh --disable-up-arrow;  zsh-cache-comp atuin gen-completions --shell zsh;" }
"aqua:aws/aws-cli"                 = { version = "latest" }
"aqua:bootandy/dust"               = { version = "latest" }
"aqua:BurntSushi/ripgrep"          = { version = "latest", postinstall = "zsh-cache-comp  rg --generate complete-zsh" }
"aqua:carapace-sh/carapace-bin"    = { version = "latest" }
"aqua:charmbracelet/crush"         = { version = "latest", postinstall = "zsh-cache-comp crush completion zsh;" }
"aqua:charmbracelet/freeze"        = { version = "latest" }
"aqua:charmbracelet/glow"          = { version = "latest" }
"aqua:charmbracelet/skate"         = { version = "latest" }
"aqua:ClementTsang/bottom"         = { version = "latest" }
# "aqua:crates.io/broot"             = { version = "latest" }
"aqua:cue-lang/cue"                = { version = "latest" }
"aqua:dandavison/delta"            = { version = "latest", postinstall = "zsh-cache-comp delta --generate-completion zsh;" }
"aqua:denisidoro/navi"             = { version = "2.23.0", postinstall = "zsh-cache-init navi widget zsh;" }
"aqua:direnv/direnv"               = { version = "latest" }
"aqua:ducaale/xh"                  = { version = "latest" }
"aqua:dylanaraps/neofetch"         = { version = "latest" }
"github:eza-community/eza"           = { version = "latest" }
"aqua:FiloSottile/age"             = { version = "latest" }
"aqua:FiloSottile/mkcert"          = { version = "latest" }
"aqua:getsops/sops"                = { version = "latest" }
"github:Giammarco-Ferranti/deja"   = { version = "latest", postinstall = "zsh-cache-init deja init zsh" }
"aqua:gopasspw/gopass"             = { version = "latest" }
"aqua:ip7z/7zip"                   = { version = "latest" }
"aqua:jdx/mise"                    = { version = "latest", postinstall = "mise plugins update --yes;\n  zsh-cache-comp mise completion zsh;" }
"aqua:jj-vcs/jj"                   = { version = "latest", postinstall = "zsh-cache-comp jj util completion zsh;" }
"aqua:jqlang/jq"                   = { version = "latest" }
"aqua:junegunn/fzf"                = { version = "latest" }
"aqua:Lifailon/lazyjournal"        = { version = "latest" }
"aqua:mikefarah/yq"                = { version = "latest" }
"aqua:mr-karan/doggo"              = { version = "latest", postinstall = "zsh-cache-comp doggo completions zsh;" }
"aqua:neovim/neovim"               = { version = "latest" }
"aqua:rossmacarthur/sheldon"       = { version = "latest", postinstall = "zsh-cache-comp sheldon completions --shell zsh;" }
"aqua:sachaos/viddy"               = { version = "latest" }
"aqua:sharkdp/bat"                 = { version = "latest", postinstall = "zsh-cache-comp bat --completion zsh;" }
"aqua:sharkdp/fd"                  = { version = "latest" }
"aqua:sharkdp/vivid"               = { version = "latest" }
"aqua:showwin/speedtest-go"        = { version = "latest" }
"aqua:sigstore/cosign"             = { version = "latest" }
"aqua:sxyazi/yazi"                 = { version = "latest" }
"aqua:tailscale/tailscale"         = { version = "latest" }
"aqua:txn2/kubefwd"                = { version = "latest" }
"aqua:wagoodman/dive"              = { version = "latest" }
"aqua:watchexec/watchexec"         = { version = "latest" }
"aqua:zellij-org/zellij"           = { version = "latest" }
"github:michel-kraemer/zsh-patina" = { version = "latest", postinstall = "zsh-cache-init zsh-patina activate;" }
"npm:@anthropic-ai/claude-code"    = { version = "latest" }
"npm:@openai/codex"                = { version = "latest" }



